name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Run Unit Tests
        run: npm test

      - name: Push Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag myapp:latest mydockerhub/myapp:latest
          docker push mydockerhub/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_ELASTIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull mydockerhub/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 80:3000 --name myapp mydockerhub/myapp:latest
